# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9672b4c65a68d77a1a6222696f9522c1ef713e3ded93d1ce25ae36a4d7cf76480572e82c478f342371e5ccfede8ab2340fba01bd63027c442f45fd926ac0aede

test:
  secret_key_base: 5c5fd8ee23baa7e6ab93fbb0e3e758f3ba0d3739ccb2c525bc29f837895e7525a77745d0cdcf0d5a8f6fd03a1ebc24698b1ef6b913f254252fb6ea0b02610c34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
